### ISSUE TITLE
How can I add more attributes

### ISSUE THREAD

**Issue by PotatoStewer** [HashLips/hashlips_art_engine#1423]
So in the json file the attributes are adjusted to the names of different layers, I want to add a display type of "string", the value or the specific name of the layer as "value", and the percentage rarity of the layers. Am I able to do it via the engine?
Thank you!

**Comment by bolshoytoster** [comment]
@PotatoStewer you could have another layer but just have all of the images blank.

**Comment by PotatoStewer** [comment]
But would that just add a new trait type and value?
I wanted to add a "display_type" to it 
How would I able to do that? 

"display_type": "string",
      "trait_type": "Background",
      "value": "Army Green",
      "percentage": "5.56%"

Thank you!

**Comment by bolshoytoster** [comment]
@PotatoStewer oh, you'd probably have to add something like:
```js
    display_type: "string",
    percentage: `${_element.layer.selectedElement.weight}%`,
```
to line ~178 in `src/main.js`:
https://github.com/HashLips/hashlips_art_engine/blob/d8ee279043d2d4a8de3bdfac0d89d0e966fb04a2/src/main.js#L178-L179

That would only work if your weights on each layer added up to 100, otherwise the percentage will have to be calculated which takes effort (this):

---

You can calculate the percentage by adding
```js
let weightProportions = {};
```
to ~line 33 in `src/main.js:
https://github.com/HashLips/hashlips_art_engine/blob/d8ee279043d2d4a8de3bdfac0d89d0e966fb04a2/src/main.js#L32-L34

Change the `percentage: ...` line you added to
```js
    percentage: `${_element.layer.selectedElement.weight * weightProportions[_element.layer.name]}%`,
```

Then add
```js
    if (!weightProportions[layer.name])
      weightProportions[layer.name] = 100 / totalWeight;
```
to line ~288:
https://github.com/HashLips/hashlips_art_engine/blob/d8ee279043d2d4a8de3bdfac0d89d0e966fb04a2/src/main.js#L288-L289

Make sure you save and the attributes will be in the metadata next time you generate.

**Comment by PotatoStewer** [comment]
Awesome, that answers my questions, thank you!!
