### ISSUE TITLE
Output images without color

### ISSUE THREAD

**Issue by nomancoder** [HashLips/hashlips_art_engine#147]
I tried this on my project the dimension of images are 1920 X 1080 but this generate bad quality output without colors.

**Comment by Anchii88** [comment]
i have this problem too - some of the generated images don't get all of the layers. i think it happens when for example "backgroundimage red" is used for image 1 and then for image 2 the algorithm wants to have "backroundimage red" too. then the image 2 won't have any background. but i don't get where this is happening or how i can correct that...
