### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: ENOENT, No such file or directory 

### ISSUE THREAD

**Issue by sayinmehmet47** [HashLips/hashlips_art_engine#276]
![image](https://user-images.githubusercontent.com/75525090/142404762-05f1d889-9afa-4888-a4bc-f3f326f8c166.png)

I renamed all files and removed all dashes but throw errors.
Also when I try the template at the beginning, without making any change and run the command . 
```js
node index.js
```
I installed all dependencies also
it is throwing the same error. Am I have to change anything in configure.js or in package.json at the beginning?

**Comment by turcoder** [comment]
Hi @sayinmehmet47   , i had the same issue and in my case the problem was the directory of the project, maybe it was a permissions issue. 

What i have done was , to move the project to under "C:\Users\{Username}" folder. and this worked to me.
Maybe you can try to change permissions of your folder containing the project or move it to some dir. that you sure it has permissions.

Hope this works for you, 
cheers.
