### ISSUE TITLE
How to make ORIGINAL combinations.

### ISSUE THREAD

**Issue by tontonfriends** [HashLips/hashlips_art_engine#37]
Assuming there are 4 layers of hat, face, clothes and acc,
When the best(ideal) combination of hat, face, clothes, and Acc is 1,1,1,1 = (hat)1, (face)1, (clothing)1, (Acc)1
In the case of random generation of 10, the combination of 1,1,1,1 may not come out.
ex) 1,0,0,1 / 1,0,0,2 / 1,1,0,1 / 1,1,1,2 / 1,2,1,1 / 1,0,1,1 / 0,1,1,1 / 1,1,0,0 / 0,1,2,0 / 0,0,2,2

**How can I make that 1,1,1,1 must be included?**

**Comment by burmestr** [comment]
If there are too many possible variations (less than you want to generate) but you have this idea of including some "must have" variations.. I am not sure how many of those "must have" variations you got there, but just add it manually in the end, make those PNGs in Photoshop and make up json for them with hands, otherwise just generate more to make sure all variations are included. It doesn't make sense adding function to create some specific variatons before randomizing other varitions... It's a wierd task.
