### ISSUE TITLE
Please help! Re-generation by DNA

### ISSUE THREAD

**Issue by Intelligencybar** [HashLips/hashlips_art_engine#490]
Simple question.  Can I generate images by dna and not randomly?  I have a collection that I want to iterate over because the metadata was not saved on the first generation.  If anyone knows how to do this, I will be very grateful for the answer!

**Comment by psavva** [comment]
The current implementation does not support what you suggest.  Since you don't know the layers, you have 2 choices.

1) regenerate the collection.  I cannot see a reason why you would need that exact faulty collection your generated.  Fix the problem and generate from beginning where everything is correct.
Very easy

2) customize the generation to load all the DNA hashes, assuming you have them, and generate every combination until you get your hashes in your file.  Depending on the layers you have, could take second or hours possibly to generate everything.  This would require a big change in the generator method. 
No so easy.
