### ISSUE TITLE
Repeats the same feature and  "#" sign is not working

### ISSUE THREAD

**Issue by Researcher33** [HashLips/hashlips_art_engine#542]
Even though I wrote #1 next to the layer, it's using it twice. I did not change any feature of the program. Also, it does not use as many layers as the number written after the # sign.

**Comment by LordSpecterOne** [comment]
That number is not the number of times to use the layer.  It's an arbitrary weighted number.   Main.js line 279 is the function to reference to see how the weighted number is used.  I personally don't understand the math behind this, but it is not a 1 to 1 value like you're thinking.

My personal feelings aside (I hate them in AGILE methodologies as well!) think of weighted number as...

Think of taking a course in school. Final Exam is 20% of your overall course grade. So that 20% is the weighted value of that exam vs your overall course grade.

So, when you have multiple options/layers like this engine.  A folder of eye colors for example.  You want red to be super rare.  A #1 would only give it a weighted value of 1 vs the other options in that one folder.  Depending on the number of other options you have in that folder, 10 for example.  Your #1 is bound to show up multiple times.  If you have 10 color options and you're spitting out a 10k collection.  Your red color would bound to be showing up multiple times.

If you have 1000 eye color options and you put #1.  That weighted value of the red showing up would be ultra-rare.   So, 1000 eye color options and you're spitting out a 10k collection.  Your red color would definitely only limited.

So, options to try to reduce the occurrence... increase the weighted value of the other options in the folder.  Lower your final collection count.  For a 10k collection, a folder with 3 options.  Setting 1 to #1, and the others to say #10000.  You'll find that #1 will only appear maybe once or twice.

**Comment by Researcher33** [comment]
Having the rarity setting as % really pushes the job even more. If the numbers entered after # were set as the number of layers, a simpler, easier and more precise rarity result would be obtained. NFT markets already calculate rarity percentages.

**Comment by LordSpecterOne** [comment]
That's just not how this codebase works.  You'll have to modify the script to your tastes to get a percentage based forumal..  Weighted values are used a lot in large, complicated samples and statistics.  It is a common practice.  As for using each layer once... only way to attempt that is to make them all even.  Completely remove the # number off the file names. They will all have equal weighted value.

So your example, if your growEditionSizeTo is 10k.  There are no weighted values assigned to your files in the Background folder.  And you have 10k background files.  It should work as your expecting.  You'll get a bunch of DNA already exists warnings but that's to be expected.  The end result will be your 10k.

**Comment by Researcher33** [comment]
But when you add the properties in the other folder, there is no certainty. Thousands of combinations...
