### ISSUE TITLE
Glitched Layers ....

### ISSUE THREAD

**Issue by IRONPOOL91** [HashLips/hashlips_art_engine#600]
Hi, First of all, thanks for such an amazing engine, now the problem is when I am running the engine certain background layers get glitched while the others remain exactly as they should, the shared file shows an example of how a layer should be looking like and how it turns out to be.

![5](https://user-images.githubusercontent.com/95302177/151108959-78cf1b6e-982e-4538-a7df-adc5282f2237.png)
![vorolightpurpleskybluelightyellow #50](https://user-images.githubusercontent.com/95302177/151109014-12a6f22a-21d8-434e-929c-e35e8ef8331d.png)
s

Regards

**Comment by thepeanutgalleryandco** [comment]
Can you perhaps zip your folder and share it so that we can attempt to generate the build with your layer files to see if we get the same result? Perhaps leave layer items that generate fine and then the ones that glitch, along with your src/config.js and src/main.js files as is.

Otherwise it will be very difficult to replicate and debug. Please remove any apikeys if they exist in your files.

**Comment by IRONPOOL91** [comment]
ok

**Comment by IRONPOOL91** [comment]
> Can you perhaps zip your folder and share it so that we can attempt to generate the build with your layer files to see if we get the same result? Perhaps leave layer items that generate fine and then the ones that glitch, along with your src/config.js and src/main.js files as is.
> 
> Otherwise it will be very difficult to replicate and debug. Please remove any apikeys if they exist in your files.

[src.zip](https://github.com/HashLips/hashlips_art_engine/files/7939238/src.zip)

**Comment by RequiemDreams** [comment]
having the same issue could someone please shed some light been trying to fix for last 4 days
